#include "lvgl.h"

#define SET_IMG(obj, img) lv_image_set_src(obj, &img);

LV_IMAGE_DECLARE(IMG_MOSTLY_CLEAR_NIGHT);
LV_IMAGE_DECLARE(IMG_ISOLATED_SCATTERED_TSTORMS_DAY);
LV_IMAGE_DECLARE(IMG_PARTLY_CLOUDY);
LV_IMAGE_DECLARE(IMG_SCATTERED_SHOWERS_DAY);
LV_IMAGE_DECLARE(IMG_HEAVY_SNOW);
LV_IMAGE_DECLARE(IMG_MOSTLY_CLOUDY_DAY);
LV_IMAGE_DECLARE(IMG_TORNADO);
LV_IMAGE_DECLARE(IMG_PARTLY_CLOUDY_NIGHT);
LV_IMAGE_DECLARE(IMG_MOSTLY_CLOUDY_NIGHT);
LV_IMAGE_DECLARE(IMG_CLEAR_NIGHT);
LV_IMAGE_DECLARE(IMG_ARROW);
LV_IMAGE_DECLARE(IMG_MOSTLY_SUNNY);
LV_IMAGE_DECLARE(IMG_WINTRY_MIX_RAIN_SNOW);
LV_IMAGE_DECLARE(IMG_PLACEHOLDER);
LV_IMAGE_DECLARE(IMG_SNOW_SHOWERS_SNOW);
LV_IMAGE_DECLARE(IMG_HAZE_FOG_DUST_SMOKE);
LV_IMAGE_DECLARE(IMG_STRONG_TSTORMS);
LV_IMAGE_DECLARE(IMG_CLOUDY);
LV_IMAGE_DECLARE(IMG_SUNNY);
LV_IMAGE_DECLARE(IMG_BLIZZARD);
LV_IMAGE_DECLARE(IMG_SCATTERED_SHOWERS_NIGHT);
LV_IMAGE_DECLARE(IMG_HEAVY_RAIN);
LV_IMAGE_DECLARE(IMG_BLOWING_SNOW);
LV_IMAGE_DECLARE(IMG_FLURRIES);
LV_IMAGE_DECLARE(IMG_ISOLATED_SCATTERED_TSTORMS_NIGHT);
LV_IMAGE_DECLARE(IMG_SHOWERS_RAIN);
LV_IMAGE_DECLARE(IMG_DRIZZLE);
LV_IMAGE_DECLARE(IMG_SLEET_HAIL);
