#include "watch.hpp"

#include "lvgl.h"
#include "fonts.h"

#include "math.h"

#define DEG2RAD 0.017453292519943295

// Radius, angle (degrees)
// 0˚ is pointing to the right, angle goes counter-clockwise
#define POLAR(r, t) cosf(DEG2RAD *t) * r, sinf(DEG2RAD *t) * r

extern lv_obj_t *main_screen;
extern lv_obj_t *hor_layer;
extern lv_obj_t *ver_layer;
extern lv_obj_t *lower_layer;

extern lv_obj_t *watchscr;
extern lv_obj_t *musicscr;

// RAM-resident copies of the generated const flash fonts with NotoEmoji
// installed as the fallback. Initialized at the top of Display::ui_init.
// Use these in place of the originals on any label that renders user-
// supplied text (notifications, music metadata) so emoji codepoints
// resolve through the fallback chain instead of dropping out as missing
// glyphs. Declared here rather than in fonts.h because fonts.h is
// regenerated by fonts.py and would lose any hand-edits.
extern lv_font_t ProductSansBold_30_emoji;
extern lv_font_t ProductSansBold_24_emoji;
extern lv_font_t ProductSansRegular_20_emoji;
extern lv_font_t ProductSansBold_16_emoji;
extern lv_font_t ProductSansRegular_14_emoji;

lv_obj_t *create_screen(lv_obj_t *parent);
lv_obj_t *create_valuearc(lv_obj_t *parent, const char *symbol);

// Shared accent styles + current accent color. Live-update mechanism for
// the theme primary: instead of capturing lv_theme_get_color_primary into
// a per-widget local style, widgets attach one of these shared styles via
// lv_obj_add_style — when the settings screen calls apply_accent_color(),
// every widget that has the style attached repaints with the new color.
//
// Use g_accent_color for the rare dynamic case where a widget toggles
// between accent and a neutral gray at click time (AM/PM, focused-field
// border in the alarm editor): the global stays in sync so the next
// toggle reads the up-to-date color.
extern lv_color_t g_accent_color;
extern lv_style_t accent_bg_style;
extern lv_style_t accent_text_style;
extern lv_style_t accent_border_style;
extern lv_style_t accent_line_style;
extern lv_style_t accent_arc_indicator_style;
void apply_accent_color(lv_color_t c);
lv_obj_t *create_app(lv_obj_t *parent, const char *icon, const char *name, lv_event_cb_t event_cb = nullptr);
lv_obj_t *create_app(lv_obj_t *parent, const char *icon, const char *name, lv_obj_t *screen, bool appsonly = false);
lv_obj_t *create_setting(lv_obj_t *parent, const char *name, bool state, lv_event_cb_t event_cb);

// lv_obj_t *rotarywatch_create(lv_obj_t *parent);
// void rotarywatch_update();

lv_obj_t *analogwatch_create(lv_obj_t *parent);
void analogwatch_update();

// lv_obj_t *timescreen_create(lv_obj_t *parent);
// void timescreen_update();

lv_obj_t *watchface_create(lv_obj_t *parent);

lv_obj_t *quicksettings_create(lv_obj_t *parent);
lv_obj_t *apps_screen_create(lv_obj_t *parent);

lv_obj_t *stopwatch_create(lv_obj_t *parent);
lv_obj_t *timerscr_create(lv_obj_t *parent);
lv_obj_t *alarmscr_create(lv_obj_t *parent);
lv_obj_t *imu_screen_create(lv_obj_t *parent);
lv_obj_t *calculator_create(lv_obj_t *parent);
lv_obj_t *dice_create(lv_obj_t *parent);
lv_obj_t *schedule_screen_create(lv_obj_t *parent);
lv_obj_t *notifications_screen_create(lv_obj_t *parent);
lv_obj_t *music_create(lv_obj_t *parent);
lv_obj_t *draw_create(lv_obj_t *parent);

// Show the latest pending notification (if any) as the active screen with
// no animation. Call from Watch::wakeup() before the backlight comes on so
// the user never sees a frame of the underlying screen when a notification
// triggered the wake.
void notification_popup_present_now();

// Dismiss any active popup with no animation. Call from Watch::sleep()
// after the backlight has fully faded so the popup→prev-screen transition
// happens entirely off-screen.
void notification_popup_dismiss_now();

lv_obj_t *settingsscreen_create();

// Theme palette accessors, defined in debug.cpp. The settings screen
// owns the palette table; ui_init reads from it at boot to apply the
// saved primary color.
uint8_t settings_color_count();
lv_color_t settings_color_at(uint8_t idx);

// Rotation setter that also persists the value to NVS. Quick-settings
// rotate icon calls this so the choice survives reboots.
void settings_apply_rotation(lv_display_rotation_t rot);