#include "watch.hpp"

#include "lvgl.h"
#include "fonts.h"

#include "math.h"

#define DEG2RAD 0.017453292519943295

// Radius, angle (degrees)
// 0˚ is pointing to the right, angle goes counter-clockwise
#define POLAR(r, t) cosf(DEG2RAD *t) * r, sinf(DEG2RAD *t) * r

extern lv_obj_t *main_screen;
extern lv_obj_t *hor_layer;
extern lv_obj_t *ver_layer;
extern lv_obj_t *lower_layer;

extern lv_obj_t *watchscr;

extern lv_obj_t *musicscr;
extern lv_obj_t *settings_screen;
extern lv_obj_t *calculator_screen;
extern lv_obj_t *schedule_screen;
extern lv_obj_t *metronome_screen;
extern lv_obj_t *homeassistant_screen;
extern lv_obj_t *units_screen;

// RAM-resident copies of the generated const flash fonts with NotoEmoji
// installed as the fallback. Initialized at the top of Display::ui_init.
// Use these in place of the originals on any label that renders user-
// supplied text (notifications, music metadata) so emoji codepoints
// resolve through the fallback chain instead of dropping out as missing
// glyphs. Declared here rather than in fonts.h because fonts.h is
// regenerated by fonts.py and would lose any hand-edits.
extern lv_font_t ProductSansBold_30_emoji;
extern lv_font_t ProductSansBold_24_emoji;
extern lv_font_t ProductSansBold_16_emoji;
extern lv_font_t ProductSansRegular_20_emoji;
extern lv_font_t ProductSansRegular_16_emoji;
extern lv_font_t ProductSansRegular_14_emoji;

// Same RAM-copy pattern but with FontAwesome_16 as the fallback — for
// labels that mix regular text with FA icon glyphs in one string
// (weather humidity / UV values).
extern lv_font_t ProductSansRegular_16_fa;
extern lv_font_t ProductSansRegular_24_fa;

lv_obj_t *create_screen(lv_obj_t *parent);
lv_obj_t *create_valuearc(lv_obj_t *parent, const char *symbol);

// Shared accent styles + current accent color. Live-update mechanism for
// the theme primary: instead of capturing lv_theme_get_color_primary into
// a per-widget local style, widgets attach one of these shared styles via
// lv_obj_add_style — when the settings screen calls apply_accent_color(),
// every widget that has the style attached repaints with the new color.
//
// Use g_accent_color for the rare dynamic case where a widget toggles
// between accent and a neutral gray at click time (AM/PM, focused-field
// border in the alarm editor): the global stays in sync so the next
// toggle reads the up-to-date color.
extern lv_color_t g_accent_color;
extern lv_style_t accent_bg_style;
extern lv_style_t accent_text_style;
extern lv_style_t accent_border_style;
extern lv_style_t accent_line_style;
extern lv_style_t accent_arc_indicator_style;
void apply_accent_color(lv_color_t c);
lv_obj_t *create_app(lv_obj_t *parent, const char *icon, const char *name, lv_event_cb_t event_cb = nullptr);
lv_obj_t *create_app(lv_obj_t *parent, const char *icon, const char *name, lv_obj_t *screen, bool appsonly = false);
lv_obj_t *create_setting(lv_obj_t *parent, const char *name, bool state, lv_event_cb_t event_cb);

char *getbaticon(bool charging, uint8_t percent);

lv_obj_t *rotarywatch_create(lv_obj_t *parent);
void rotarywatch_update();

lv_obj_t *analogwatch_create(lv_obj_t *parent);
void analogwatch_update();

lv_obj_t *timescreen_create(lv_obj_t *parent);
void timescreen_update();

lv_obj_t *wordwatch_create(lv_obj_t *parent);
void wordwatch_update();

lv_obj_t *divewatch_create(lv_obj_t *parent);
void divewatch_update();

lv_obj_t *watchface_create(lv_obj_t *parent);
extern lv_obj_t *watchface;

// Watch-face picker API. watchface_set_active() persists the new index in
// NVS and live-swaps the on-screen face obj.
uint8_t watchface_count();
const char *watchface_name_at(uint8_t idx);
uint8_t watchface_active_idx();
void watchface_set_active(uint8_t idx);

lv_obj_t *quicksettings_create(lv_obj_t *parent);
lv_obj_t *apps_screen_create(lv_obj_t *parent);

lv_obj_t *stopwatch_create(lv_obj_t *parent);
lv_obj_t *timerscr_create(lv_obj_t *parent);
lv_obj_t *alarmscr_create(lv_obj_t *parent);
// Overwrite the local N_ALARMS slots with a Gadgetbridge alarm array
// (the "d" field of {t:"alarm"}). Handles h→12h conversion, NVS
// persist, and refreshes any live row widgets under lvgl_port_lock.
// `arr` must be a cJSON array; caller is responsible for the outer
// message parse and the type check. Extra entries past N_ALARMS are
// dropped; short arrays leave trailing slots disabled.
struct cJSON;
extern "C" void alarm_apply_from_gb(struct cJSON *arr);
lv_obj_t *imu_screen_create(lv_obj_t *parent);
lv_obj_t *calculator_create(lv_obj_t *parent);
lv_obj_t *dice_create(lv_obj_t *parent);
lv_obj_t *schedule_screen_create(lv_obj_t *parent);
lv_obj_t *notifications_screen_create(lv_obj_t *parent);
lv_obj_t *music_create(lv_obj_t *parent);
lv_obj_t *homeassistant_create(lv_obj_t *parent);
lv_obj_t *units_create(lv_obj_t *parent);

void homeassistant_response_recieved(const char *resp_json);
// Tear down the music screen + its 1 Hz updater. Pairs with
// music_create. Used by ui_init's music-visibility tick to remove the
// screen from hor_layer after a few minutes of paused playback.
void music_destroy(void);
// Force-refresh the music screen NOW. Watch::wakeup calls this so
// any musicstate/musicinfo/album-art changes that arrived via BLE
// while the watch was asleep are reflected on the screen the instant
// the user looks at it, instead of waiting up to a second for the
// 1 Hz timer to tick. Also resets the position-interpolation anchor
// so the slept time doesn't get added to the displayed playback
// position. No-op if the music screen hasn't been created.
void music_refresh(void);
lv_obj_t *weather_create(lv_obj_t *parent);
lv_obj_t *metronome_create(lv_obj_t *parent);

// Standalone $1 unistroke recognizer screen. Screen widgets allocate on
// first call; cheap until then.
lv_obj_t *unistroke_create(lv_obj_t *parent);

// Adds the "Unistroke" entry to the apps grid. Call AFTER ble.init() —
// the BT controller's boot-time malloc needs internal SRAM that even one
// additional pre-BLE widget allocation is enough to starve.
void unistroke_register_app();

// Set at the end of ui_init so post-boot code can append app entries.
extern lv_obj_t *g_appsscreen;

// Show the latest pending notification (if any) as the active screen with
// no animation. Call from Watch::wakeup() before the backlight comes on so
// the user never sees a frame of the underlying screen when a notification
// triggered the wake.
void notification_popup_present_now();

// Dismiss any active popup with no animation. Call from Watch::sleep()
// after the backlight has fully faded so the popup→prev-screen transition
// happens entirely off-screen.
void notification_popup_dismiss_now();

lv_obj_t *settingsscreen_create();

// Theme palette accessors, defined in debug.cpp. The settings screen
// owns the palette table; ui_init reads from it at boot to apply the
// saved primary color.
uint8_t settings_color_count();
lv_color_t settings_color_at(uint8_t idx);
// Hex form ("#RRGGBB") of the palette entry at idx — matches what
// gets written into config.json under settings.themecolor. Out-of-
// range idx clamps to 0.
const char *settings_color_hex_at(uint8_t idx);
// Reverse mapping: hex string → palette index. Case-insensitive.
// Returns UINT8_MAX when the hex isn't in the palette (i.e. a custom
// picker-chosen colour) so callers can tell "matches palette entry 0"
// from "no palette match".
uint8_t settings_color_idx_from_hex(const char *hex);

// Parse a "#RRGGBB" (or "RRGGBB", case-insensitive) hex string into an
// lv_color_t. Accepts arbitrary hex — not restricted to the palette —
// so a hand-edited config.json or the built-in color picker can carry
// any accent colour through boot. Malformed input falls back to
// SETTINGS_PALETTE[0] rather than throwing so the watch still boots.
lv_color_t settings_color_from_hex(const char *hex);

// Rotation setter that also persists the value to NVS. Quick-settings
// rotate icon calls this so the choice survives reboots.
void settings_apply_rotation(lv_display_rotation_t rot);